name: Build and Deploy VotingWeb App
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET Core 9
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 9.0.x

      - name: Restore NuGet Packages
        run: dotnet restore ${{ vars.VOTINGWEB_APPPATH }}

      - name: Build
        run: dotnet build ${{ vars.VOTINGWEB_APPPATH }} --configuration ${{ vars.BUILDCONFIGURATION }} --no-restore

      - name: Publish
        run: dotnet publish ${{ vars.VOTINGWEB_APPPATH }} --configuration ${{ vars.BUILDCONFIGURATION }} --output  ${{ github.workspace }}/VoteWeb --no-restore
    
      
      - name: Archive Files
        uses: actions/upload-artifact@v4
        with:
          name: drop
          path: ${{ github.workspace }}/VoteWeb

  deploy:
    permissions:
      id-token: write
    needs: build
    runs-on: self-hosted
    environment: 'production'
    steps:
      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - uses: actions/download-artifact@master
        with:
          name: drop
          path: ${{ github.workspace }}/VoteWeb
      
      - name: Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ vars.VOTINGWEB_APP_NAME }}
          package: ${{ github.workspace }}/VoteWeb
          slot-name: production
